#
#  makefile.env - RPN (Reverse Polish) calculator simulator.
#
#  Copyright(C) 2024 - macmpi - MT
#
#  This  program is free software: you can redistribute it and/or modify it
#  under  the terms of the GNU General Public License as published  by  the
#  Free  Software Foundation, either version 3 of the License, or (at  your
#  option) any later version.
#
#  This  program  is distributed in the hope that it will  be  useful,  but
#  WITHOUT   ANY   WARRANTY;   without even   the   implied   warranty   of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
#  Public License for more details.
#
#  You  should have received a copy of the GNU General Public License along
#  with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Note separator (tab) at the beginning of the line CANNOT be a space..!
#
#  01 Apr 24         - Initial version - MT
#

PROGRAM		=  x11-calc

BIN		= bin
SRC		= src
PRG		= prg
ROM		= rom
IMG		= img

DESTDIR		=
prefix		= $$HOME/.local

