#
#  makefile.backup - RPN (Reverse Polish) calculator simulator.
#
#  Copyright(C) 2024 - macmpi - MT
#
#  This  program is free software: you can redistribute it and/or modify it
#  under  the terms of the GNU General Public License as published  by  the
#  Free  Software Foundation, either version 3 of the License, or (at  your
#  option) any later version.
#
#  This  program  is distributed in the hope that it will  be  useful,  but
#  WITHOUT   ANY   WARRANTY;   without even   the   implied   warranty   of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
#  Public License for more details.
#
#  You  should have received a copy of the GNU General Public License along
#  with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#  Note separator (tab) at the beginning of the line CANNOT be a space..!
#
#  01 Apr 24         - Spin off makefile for backup - macmpi
#                    - Modified to work on Tru64 Linux - MT
#  03 Apr 24         - Fixed possible issue with use of date - MT
#                    - Added new makefiles - MT
#

include makefile.env

FILES	= `ls makefile makefile.common makefile.env makefile.cde makefile.backup makefile.*.[0-9] $(SRC)/makefile $(SRC)/makefile.common $(SRC)/makefile.linux $(SRC)/makefile.bsd $(SRC)/makefile.osf1 $(SRC)/makefile.*.[0-9] 2>/dev/null || true`
SOURCE	= `ls $(SRC)/*.c $(SRC)/*.c.[0-9] $(SRC)/*.h $(SRC)/*.h.[0-9] $(SRC)/*.in $(SRC)/*.in.[0-9] 2>/dev/null || true`
DATA	= `ls $(ROM)/x11-calc*.rom $(ROM)/x11-calc*.rom.[0-9] $(PRG)/x11-calc*.dat $(PRG)/x11-calc*.dat.[0-9] 2>/dev/null || true`
IMAGES	= `ls $(SRC)/*.ico $(SRC)/*.ico.[0-9] $(SRC)/*.png $(SRC)/*.png.[0-9] $(SRC)/*.svg $(SRC)/*.svg.[0-9] $(IMG)/*.png $(IMG)/*.png.[0-9] 2>/dev/null || true`
OTHERS	= `ls $(SRC)/make.com  $(SRC)/make.com.[0-9] *.md *.md.[0-9] .gitignore .gitattributes 2>/dev/null || true`

_date	= `date +'%Y%m%d%H%M'`

backup:
	tar -cpf ..\/$(PROGRAM)-$(_date).tar $(FILES)
	tar -rpf ..\/$(PROGRAM)-$(_date).tar $(SOURCE)
	tar -rpf ..\/$(PROGRAM)-$(_date).tar $(DATA)
	tar -rpf ..\/$(PROGRAM)-$(_date).tar $(IMAGES)
	tar -rpf ..\/$(PROGRAM)-$(_date).tar $(OTHERS)
	echo "$(PROGRAM)-$(_date).tar"
